; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32dev, esp32-s3dev-50, esp32-s3dev-28

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_deps =
	lvgl/lvgl@8.3.9
	https://github.com/knolleary/pubsubclient.git
	ArduinoJson@6.21.5
	FS
	SD
	https://github.com/PaulStoffregen/OneWire.git#v2.3.8
	https://github.com/milesburton/Arduino-Temperature-Control-Library.git#v4.0.3
	https://github.com/ESP32Async/ESPAsyncWebServer.git
	https://github.com/tuan-karma/ESP32_WiFiClientSecure.git
	https://github.com/lvgl/lv_lib_png.git
	adafruit/Adafruit NeoPixel@^1.12.0
	https://github.com/kikuchan/pngle.git
	https://github.com/moononournation/Arduino_GFX.git#v1.4.9
build_flags = 
	-D LV_CONF_PATH="${PROJECT_DIR}/resources/lv_conf.h"
	-D LV_LVGL_H_INCLUDE_SIMPLE
	-DXTOUCH_NET_SD_WRITE_YIELD_EVERY_BYTES=4096
	-DPNGLE_NO_GAMMA_CORRECTION
	!python scripts/version.py

extra_scripts = 
	pre:scripts/pre-build.py

build_src_filter = 
	+<*>
	-<xtouch/bbl/bbl-errors_old.c>
[LovyanGFX]
lib_deps =
	${env.lib_deps} 
	https://github.com/tac5551/LovyanGFX.git

[Arduino_GFX]
lib_deps =
	${env.lib_deps} 
	https://github.com/moononournation/Arduino_GFX.git#v1.4.9

[env:esp32dev]
board = esp32dev
board_build.filesystem = littlefs
board_build.partitions = min_spiffs.csv
monitor_filters = esp32_exception_decoder
lib_deps =
	${LovyanGFX.lib_deps}
build_src_filter = 
	${env.build_src_filter}
	-<font/>   ; 2.8は日本語フォント未使用のため両方除外
build_flags = 
	${env.build_flags} 
	-D__XTOUCH_SCREEN_28__
	-DLGFX_ESP32_3248S035R
	-DLGFX_ESP32_3248S035C
	; -O0

extra_scripts = 
	${env.extra_scripts} 
	post:scripts/post-build.py

[env:esp32-s3dev-50]
board = esp32-s3-devkitc1-n16r8
lib_deps =
	${LovyanGFX.lib_deps}
build_src_filter = 
	${env.build_src_filter}
	-<font/lv_font_notosans_14.c>
build_flags = 
	${env.build_flags} 
	-DCORE_DEBUG_LEVEL=5
	-D__XTOUCH_PLATFORM_S3__
	-D__XTOUCH_SCREEN_S3_050__
	-I $PROJECT_DIR/lib/LovyanGFX/src

extra_scripts = 
	${env.extra_scripts} 
	post:scripts/post-build50.py

[env:esp32-s3dev-28]
board = esp32-s3-devkitc1-n16r8
lib_deps =
	${LovyanGFX.lib_deps}
build_src_filter = 
	${env.build_src_filter}
	-<font/lv_font_notosans_28.c>
build_flags = 
	${env.build_flags} 
	-DCORE_DEBUG_LEVEL=5
	-D__XTOUCH_PLATFORM_S3__
	-D__XTOUCH_SCREEN_S3_028__
	-I $PROJECT_DIR/lib/LovyanGFX/src

extra_scripts = 
	${env.extra_scripts} 
	post:scripts/post-build-s3-28.py

;------------------------------------------------------------------------------------------

[env:esp32-s3dev-3248]
board = esp32-s3-devkitc1-n16r8
lib_deps =
	${Arduino_GFX.lib_deps}
build_src_filter = 
	${env.build_src_filter}
	-<font/lv_font_notosans_28.c>
build_flags = 
	${env.build_flags} 
	-DCORE_DEBUG_LEVEL=1
	-D__XTOUCH_PLATFORM_S3__
	-D__XTOUCH_SCREEN_S3_3248__
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue

extra_scripts = 
	${env.extra_scripts} 
	post:scripts/post-build-s3-35.py

[env:esp32-s3dev-3248-debug]
extends = env:esp32-s3dev-3248
build_unflags =
	-DCORE_DEBUG_LEVEL=1
build_flags = 
	${env:esp32-s3dev-3248.build_flags} 
	-DCORE_DEBUG_LEVEL=5