#ifndef _UI_COMP_OPTIONALCOMPONENT_H
#define _UI_COMP_OPTIONALCOMPONENT_H

#include "../ui.h"

#ifdef __cplusplus
extern "C"
{
#endif

    // COMPONENT optionalComponent

    enum OptionalComponents
    {
        UI_COMP_OPTIONALCOMPONENT_OPTIONALCOMPONENT,

        UI_COMP_OPTIONALCOMPONENT_CHAMBER_TEMP,
        UI_COMP_OPTIONALCOMPONENT_CHAMBER_TEMP_LABEL,
        UI_COMP_OPTIONALCOMPONENT_CHAMBER_TEMP_SWITCH,

        UI_COMP_OPTIONALCOMPONENT_NEOPIXEL,
        UI_COMP_OPTIONALCOMPONENT_NEOPIXEL_LABEL,
        UI_COMP_OPTIONALCOMPONENT_NEOPIXEL_SLIDER,
        UI_COMP_OPTIONALCOMPONENT_NEOPIXEL_VALUE,


        UI_COMP_OPTIONALCOMPONENT_NEOPIXEL_NUM,
        UI_COMP_OPTIONALCOMPONENT_NEOPIXEL_NUM_LABEL,
        UI_COMP_OPTIONALCOMPONENT_NEOPIXEL_NUM_SLIDER,
        UI_COMP_OPTIONALCOMPONENT_NEOPIXEL_NUM_VALUE,

        UI_COMP_OPTIONALCOMPONENT_STACK_CHAN,
        UI_COMP_OPTIONALCOMPONENT_STACK_CHAN_LABEL,
        UI_COMP_OPTIONALCOMPONENT_STACK_CHAN_SWITCH,

        _UI_COMP_OPTIONALCOMPONENT_NUM
    };
    lv_obj_t *ui_optionalComponent_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif