#ifndef _UI_COMP_UTILCALIBRATIONCOMPONENT_H
#define _UI_COMP_UTILCALIBRATIONCOMPONENT_H

#include "../ui.h"

#ifdef __cplusplus
extern "C"
{
#endif

    // COMPONENT utilCalibrationComponent

    enum UtilCalibrationComponents
    {
        UI_COMP_UTILCALIBRATIONCOMPONENT_UTILCALIBRATIONCOMPONENT,
        UI_COMP_UTILCALIBRATIONCOMPONENT_UTILCALIBRATION_BOX,
        UI_COMP_UTILCALIBRATIONCOMPONENT_UTILCALIBRATION_LIDAR,
        UI_COMP_UTILCALIBRATIONCOMPONENT_UTILCALIBRATION_BED,
        UI_COMP_UTILCALIBRATIONCOMPONENT_UTILCALIBRATION_VIBRATION,
        UI_COMP_UTILCALIBRATIONCOMPONENT_UTILCALIBRATION_MOTOR,
        UI_COMP_UTILCALIBRATIONCOMPONENT_UTILCALIBRATION_RUN,
        _UI_COMP_UTILCALIBRATIONCOMPONENT_NUM
    };
    lv_obj_t *ui_utilCalibrationComponent_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif