#ifndef _UI_COMP_UTILCOMPONENT_H
#define _UI_COMP_UTILCOMPONENT_H

#include "../ui.h"

#ifdef __cplusplus
extern "C"
{
#endif

enum UtilComponents
{
UI_COMP_UTILCOMPONENT_UTILCOMPONENT,
UI_COMP_UTILCOMPONENT_UTILCOMPONENTPRINTERCONFIG_LINE1,
UI_COMP_UTILCOMPONENT_UTILCOMPONENTPRINTERCONFIG_LINE2,
UI_COMP_UTILCOMPONENT_UTILCOMPONENTPRINTERCONFIG_BUTTON1,
UI_COMP_UTILCOMPONENT_UTILCOMPONENTPRINTERCONFIG_BUTTON2,
UI_COMP_UTILCOMPONENT_UTILCOMPONENTPRINTERCONFIG_BUTTON3,
UI_COMP_UTILCOMPONENT_UTILCOMPONENTPRINTERCONFIG_BUTTON4,
_UI_COMP_UTILCOMPONENT_NUM
};

    lv_obj_t *ui_utilComponent_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif