#ifndef _UI_COMP_MAINSCREENSTATUS_H
#define _UI_COMP_MAINSCREENSTATUS_H

#include "../ui.h"

#ifdef __cplusplus
extern "C"
{
#endif

// COMPONENT mainScreenStatus

    enum mainScreenComponents
    {
        UI_COMP_MAINSCREENSTATUS_MAINSCREENSTATUS ,
        UI_COMP_MAINSCREENSTATUS_MAINSCREENSTATUSLOGO ,
        UI_COMP_MAINSCREENSTATUS_MAINSCREENSTATUSCAPTION ,
        UI_COMP_MAINSCREENSTATUS_MAINSCREENPREHEATBOX ,
        UI_COMP_MAINSCREENSTATUS_MAINSCREENPREHEATBOX1 ,
        UI_COMP_MAINSCREENSTATUS_MAINSCREENPREHEATBOX2 ,
        UI_COMP_MAINSCREENSTATUS_MAINSCREENPREHEATBUTTON1 ,
        UI_COMP_MAINSCREENSTATUS_MAINSCREENPREHEATBUTTON2 ,
        UI_COMP_MAINSCREENSTATUS_MAINSCREENPREHEATBUTTON3 ,
        _UI_COMP_MAINSCREENSTATUS_NUM ,
    };


    lv_obj_t *ui_mainScreenStatus_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif