#ifndef _UI_COMP_CONTROLCOMPONENT_H
#define _UI_COMP_CONTROLCOMPONENT_H

#include "../ui.h"

#ifdef __cplusplus
extern "C"
{
#endif

// COMPONENT controlComponent
enum ControlComponent {
    UI_COMP_CONTROLCOMPONENT_CONTROLCOMPONENT,
    UI_COMP_CONTROLCOMPONENT_CONTROLSCREENCOLA,
    UI_COMP_CONTROLCOMPONENT_CONTROLSCREENCOLA_CONTROLSCREENRANGE,
    UI_COMP_CONTROLCOMPONENT_CONTROLSCREENCOLA_CONTROLSCREENRANGE_CONTROLSCREENRANGEICON,
    UI_COMP_CONTROLCOMPONENT_CONTROLSCREENCOLA_CONTROLSCREENRANGE_CONTROLSCREENRANGEVALUE,
    UI_COMP_CONTROLCOMPONENT_CONTROLSCREENCOLA_CONTROLSCREENLEFT,
    UI_COMP_CONTROLCOMPONENT_CONTROLSCREENCOLA_CONTROLSCREENLEFT_CONTROLSCREENLEFTICON,
    UI_COMP_CONTROLCOMPONENT_CONTROLSCREENCOLA_CONTROLSCREENDUMMY0,
    UI_COMP_CONTROLCOMPONENT_CONTROLSCREENCOLB,
    UI_COMP_CONTROLCOMPONENT_CONTROLSCREENCOLB_CONTROLSCREENUP,
    UI_COMP_CONTROLCOMPONENT_CONTROLSCREENCOLB_CONTROLSCREENUP_CONTROLSCREENUPICON,
    UI_COMP_CONTROLCOMPONENT_CONTROLSCREENCOLB_CONTROLSCREENHOME,
    UI_COMP_CONTROLCOMPONENT_CONTROLSCREENCOLB_CONTROLSCREENHOME_CONTROLSCREENHOMEICON,
    UI_COMP_CONTROLCOMPONENT_CONTROLSCREENCOLB_CONTROLSCREENDOWN,
    UI_COMP_CONTROLCOMPONENT_CONTROLSCREENCOLB_CONTROLSCREENDOWN_CONTROLSCREENDOWNICON,
    UI_COMP_CONTROLCOMPONENT_CONTROLSCREENCOLC,
    UI_COMP_CONTROLCOMPONENT_CONTROLSCREENCOLC_CONTROLSCREENDUMMY3,
    UI_COMP_CONTROLCOMPONENT_CONTROLSCREENCOLC_CONTROLSCREENRIGHT,
    UI_COMP_CONTROLCOMPONENT_CONTROLSCREENCOLC_CONTROLSCREENRIGHT_CONTROLSCREENRIGHTICON,
    UI_COMP_CONTROLCOMPONENT_CONTROLSCREENCOLC_CONTROLSCREENDUMMY1,
    UI_COMP_CONTROLCOMPONENT_CONTROLSCREENCOLD,
    UI_COMP_CONTROLCOMPONENT_CONTROLSCREENCOLD_CONTROLSCREENBEDUP,
    UI_COMP_CONTROLCOMPONENT_CONTROLSCREENCOLD_CONTROLSCREENBEDUP_CONTROLSCREENBEDUPICON,
    UI_COMP_CONTROLCOMPONENT_CONTROLSCREENCOLD_CONTROLSCREENDUMMY2,
    UI_COMP_CONTROLCOMPONENT_CONTROLSCREENCOLD_CONTROLSCREENBEDDOWN,
    UI_COMP_CONTROLCOMPONENT_CONTROLSCREENCOLD_CONTROLSCREENBEDDOWN_CONTROLSCREENBEDDOWNICON,
    _UI_COMP_CONTROLCOMPONENT_NUM
};

    lv_obj_t *ui_controlComponent_create(lv_obj_t *comp_parent);
    void ui_event_comp_controlComponent_controlScreenRange(lv_event_t *e);
    void ui_event_comp_controlComponent_controlScreenLeft(lv_event_t *e);
    void ui_event_comp_controlComponent_controlScreenUp(lv_event_t *e);
    void ui_event_comp_controlComponent_controlScreenHome(lv_event_t *e);
    void ui_event_comp_controlComponent_controlScreenDown(lv_event_t *e);
    void ui_event_comp_controlComponent_controlScreenAxixToggle(lv_event_t *e);
    void ui_event_comp_controlComponent_controlScreenRight(lv_event_t *e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif