#include <pgmspace.h>

// Non-optimized HMS errors (legacy format)
int hms_error_length = 119;

const char *hms_error_keys[] PROGMEM = {
  "0C00040000010025",
  "0C00030000020019",
  "050003000001000E",
  "0300960000010003",
  "050003000002000E",
  "0500030000020055",
  "0501040000030001",
  "0501040000030002",
  "0500050000010021",
  "0500050000020023",
  "050005000001000F",
  "0C0003000002000E",
  "0500020000020002",
  "0C00020000020004",
  "0300900000010005",
  "0C00030000030006",
  "0300020000010009",
  "0500030000010001",
  "0C00030000020004",
  "0300900000010002",
  "0500030000010023",
  "0500030000010005",
  "0C00030000030007",
  "030001000001000A",
  "0C0003000003000B",
  "0300090000010003",
  "03000F0000010001",
  "0300090000010001",
  "050003000002000D",
  "050003000002000C",
  "0500040000010004",
  "0300940000030002",
  "0500030000010025",
  "0C0001000001000B",
  "0C00030000030010",
  "0500010000020001",
  "03000D000001000B",
  "0500010000030007",
  "0500030000020020",
  "0C00020000020006",
  "03000D0000010002",
  "03001B0000010001",
  "0500020000020001",
  "0500010000030005",
  "0500050000010001",
  "0500030000010008",
  "0300200000010002",
  "0C00010000010001",
  "0300940000020003",
  "03001B0000010002",
  "050003000001000A",
  "0500040000010001",
  "0500050000030002",
  "0C00020000010005",
  "0300030000020002",
  "0C00010000010005",
  "0500030000010004",
  "0300060000010001",
  "0300400000020001",
  "0500020000020007",
  "0300120000020001",
  "0500050000010007",
  "03001C0000010001",
  "0500010000020002",
  "03001A0000020002",
  "0300010000010008",
  "0300900000010003",
  "0300900000010001",
  "0C0003000002000F",
  "0500020000020004",
  "050003000001000B",
  "0C00030000020001",
  "03001B0000010003",
  "0C00030000010009",
  "030001000001000D",
  "0300010000030008",
  "0500040000010002",
  "0C00030000020005",
  "0300040000020001",
  "0C0003000002000C",
  "0C00010000020002",
  "0500020000020008",
  "0C00010000020007",
  "0500030000010002",
  "0300940000030001",
  "0C0003000001000A",
  "0300200000010001",
  "0C00030000020002",
  "07FF700000020003",
  "0300050000010001",
  "0500030000010006",
  "0300900000010010",
  "030001000001000C",
  "0300410000010001",
  "0500030000010021",
  "0300900000010004",
  "0300160000010001",
  "0500040000030009",
  "0C00010000010003",
  "0300930000010008",
  "03000D0000020001",
  "0C0001000001000A",
  "0C00030000030008",
  "0500040000030008",
  "0C0003000003000D",
  "0500020000020006",
  "0500030000010009",
  "0C00030000020010",
  "0500050000010006",
  "0500030000010003",
  "03001A0000020001",
  "0500040000010006",
  "0500040000020007",
  "0300010000010002",
  "0C00010000010004",
  "0C00010000020008",
  "0300170000020002",
  "0500040000010003",
  "0300090000010002"
};

const char *hms_error_values[] PROGMEM = {
  "The device malfunctioned; please restart.",
  "The Vision Encoder Plate is either not placed or incorrectly placed. Please ensure it is correctly positioned on the heatbed.",
  "Some external modules are incompatible with the printer's firmware version, which may affect normal operation. Please go to the \"Firmware\" page while connected to the internet to upgrade.",
  "The front door Hall sensor is abnormal; please check whether the connection wire is loose.",
  "Some modules are incompatible with the printer's firmware version, which may affect use. Please go to the \"Firmware\" page to update after connected to the internet, or you may update offline according to wiki.",
  "User information has expired, please log in again.",
  "Carbon rods need cleaning now.",
  "Threaded rods need lubrication now.",
  "Time-lapse kit communication error. Please reconnect the cable or restart the printer.",
  "A new version of the Timelapse Kit is available. Please connect to CyberBrick App to update this accessory separately.",
  "The accessory firmware does not match the printer. Please upgrade it on the \"Firmware\" page.",
  "Your nozzle seems to be covered with jammed or clogged material.",
  "Device login failed; please check your account information.",
  "Nozzle height seems to be too low. Please check if the nozzle is worn or tilted. Re-calibrate Lidar if the nozzle has been replaced.",
  "Chamber heating failed. The thermal resistance is too high.",
  "Purged filament may have piled up in the waste chute. Please check and clean the chute.",
  "Nozzle temperature control is abnormal. The hot end may not be installed. To heat the heating assembly without the hotend, enable Maintenance Mode in the settings.",
  "The MC module is malfunctioning; please restart the device or check device cable connection.",
  "First layer inspection is not supported for the current print job.",
  "Chamber heating failed. Possible causes: the chamber is not fully enclosed, ambient temperature is too low, or the power supply heat dissipation vent is blocked.",
  "The Chamber Temperature Control module is malfunctioning. Please restart the device.",
  "Internal service is malfunctioning. Please restart the device.",
  "Possible first layer defects have been detected. Please check the first layer quality and decide if the job should be stopped.",
  "The heatbed temperature control is abnormal; the AC board may be broken.",
  "Inspecting the first layer: please wait a moment.",
  "The resistance of the extruder servo motor is abnormal; the motor may have failed.",
  "Abnormal accelerometer data detected. Please try restarting the printer.",
  "The extruder servo motor has an open circuit. The connection may be loose, or the motor may have failed.",
  "The SD Card controller is malfunctioning.",
  "Wireless hardware error: please turn off/on WiFi or restart the device.",
  "The print file is unauthorized.",
  "Chamber temperature setting value exceed the limit, the boundary value will be set.",
  "The current firmware is abnormal. Please go to the “Firmware” page to update.",
  "Failed to calibrate Micro Lidar. Please make sure the calibration chart is clean and not obscured. Then, run machine calibration again.",
  "Your printer seems to be printing without extruding.",
  "The media pipeline is malfunctioning. Please restart the printer. If multiple attempts fail, please contact customer support.",
  "The Z axis motor seems to be stuck when moving. Please check if there is any foreign matter on the Z sliders or Z timing belt wheels.",
  "Unable to record time-lapse photography without MicroSD card inserted.",
  "Micro SD Card capacity is insufficient to cache print files.",
  "Nozzle height seems to be too high. Please check if there is residual filament attached to the nozzle.",
  "Heatbed homing failed. The environmental vibration is too great.",
  "The signal of the heatbed acceleration sensor is weak. The sensor may have fallen off or been damaged.",
  "Failed to connect to the internet. Please check the network connection.",
  "The Micro SD card is in Read-Only mode. Video recording and Timelapse recording cannot be performed. Please refer to the Wiki for assistance.",
  "The factory data of the AP board is abnormal; please replace the AP board with a new one.",
  "A system hang occurred. Please restart the device.",
  "Y-axis homing abnormal: please check if the toolhead is stuck or the Y carriage has too much resistance.",
  "Micro Lidar is offline. Please check the hardware connection.",
  "Chamber failed to reach the desired temperature. The machine will stop waiting for the chamber temperature.",
  "External disturbance was detected on the heatbed acceleeration sensor. The sensor signal wire may not be affixed.",
  "System state is abnormal; please restore to factory settings.",
  "Failed to download print job; please check your network connection.",
  "The device is in the engineering state; please pay attention to information security related matters.",
  "A new Micro Lidar was detected. Please calibrate it on the Calibration page before use.",
  "The hotend cooling fan is running slowly. It may be obstructed. Please check for debris and clean if necessary.",
  "Micro Lidar parameter is abnormal. Please contact customer support.",
  "The Filament Buffer module is malfunctioning. Please restart the device.",
  "Motor-A has an open-circuit. There may be a loose connection, or the motor may have failed.",
  "Data transmission over the serial port is abnormal; the software system may be faulty.",
  "Liveview service login failed; please check your network connection.",
  "The front cover of the toolhead fell off.",
  "MQTT Command verification failed. Please update Studio (including the network plugin) or Handy to the latest version, then restart the software and try again.",
  "The extrusion motor driver is abnormal. The MOSFET may have a short circuit.",
  "Live View camera is not connected. Please check the hardware and cable connections.",
  "The nozzle is clogged with filament.",
  "An abnormality occurs during the heating process of the heatbed; the heating modules may be broken.",
  "Chamber heating failed. The power supply temperature may be too high.",
  "Chamber heating failed. The heater may not be blowing hot air.",
  "Parts skipped before first layer inspection; the inspection is not supported for the current print.",
  "Unauthorized user: please check your account information.",
  "The screen is malfunctioning; please restart the device.",
  "Filament exposure metering failed because laser reflection is too weak on this material. First layer inspection may be inaccurate.",
  "The heatbed acceleration sensor detected unexpected continuous force. The sensor may be stuck, or the analog front end may be broken.",
  "The first layer inspection module rebooted abnormally. The inspection result may be inaccurate.",
  "An abnormality occured in heating modules of heatbed previously. To continue using your printer, please refer to the wiki to troubleshoot.",
  "The temperature of the heated bed exceeds the limit and automatically adjusts to the limit temperature.",
  "Failed to report print state; please check your network connection.",
  "First layer inspection timed out abnormally, and the current results may be inaccurate.",
  "The speed of the part cooling fan is too slow or stopped. It may be stuck, or the connector may not be plugged in properly.",
  "The build plate localization marker was not detected. Please check if the build plate is aligned correctly.",
  "Micro Lidar camera is malfunctioning. Please refer to the Wiki for troubleshooting.",
  "Time synchronization failed",
  "Micro Lidar laser parameters have drifted. Please re-calibrate your printer.",
  "The toolhead is malfunctioning. Please restart the device.",
  "Chamber cooling may be too slow. You can open the front door or top cover to help cooling if the air in the chamber is non-toxic.",
  "Your printer is in factory mode. Please contact Technical Support.",
  "X-axis homing abnormal: please check if the toolhead is stuck or the carbon rod resistance is too high.",
  "First layer inspection terminated due to abnormal Lidar data.",
  "Please check if the filament is coming out of the nozzle. If not, gently push the material and try to extrude again.",
  "The motor driver is overheating. Its radiator may be loose, or its cooling fan may be damaged.",
  "A system panic occurred. Please restart the device.",
  "The communication of chamber temperature controller is abnormal.",
  "The heatbed has worked at full load for a long time. The temperature control system may be abnormal.",
  "The system voltage is unstable. Triggering the power failure protection function.",
  "Hardware incompatible; please check the Micro Lidar.",
  "Chamber heating failed. The speed of the heating fan is too low.",
  "The extruder servo motor's current sensor is abnormal. A failure of the hardware sampling circuit may cause this.",
  "The bed temperature exceeds filament's vitrification temperature, which may cause nozzle clog. Please keep the front door of the printer open. Door open detection has been temporarily turned off.",
  "Synchronization between the Micro Lidar and MC is abnormal. Please restart your printer.",
  "Chamber temperature is abnormal. The temperature sensor at power supply may have an open circuit.",
  "Heatbed homing abnormal: there may be a bulge on the heatbed or the nozzle tip may not be clean.",
  "The Micro Lidar LED may be broken.",
  "Possible spaghetti defects were detected. Please check the print quality and decide if the job should be stopped.",
  "The door seems to be open.",
  "Detected that the extruder may not be extruding normally. Please check and decide if printing should be stopped.",
  "Streaming function error. Please check the network and try again. You can restart or update the printer if the issue persists.",
  "A system hang occurred. It has been recovered by automatic restart.",
  "Foreign objects detected on heatbed; Please check and clean the heatbed.",
  "The factory data of AP board is abnormal; please replace the AP board with a new one.",
  "The AMS module is malfunctioning. Please restart the device.",
  "The nozzle is covered with filament, or the build plate is crooked.",
  "Failed to resume previous print",
  "The bed temperature exceeds the filament's vitrification temperature, which may cause a nozzle clog. Please keep the front door of the printer open or lower the bed temperature.",
  "The heatbed temperature is abnormal; the heater may have an open circuit, or the thermal switch may be open.",
  "Micro Lidar lens seems to be dirty. Please clean the lens.",
  "Failed to get image from Live View Camera. Spaghetti and waste chute pileup detection is not available at this time.",
  "The hotend cooling fan speed is slow. It may be stuck and need cleaning.",
  "The content of print file is unreadable; please resend the print job.",
  "The extruder servo motor has a short-circuit. It may have failed."
};

// Non-optimized Device errors (legacy format)
int device_error_length = 120;

const char *device_error_keys[] PROGMEM = {
  "07004001",
  "07FF8003",
  "03004000",
  "0300800B",
  "0500400E",
  "0500403F",
  "05004006",
  "05004003",
  "05014034",
  "0300400C",
  "03008018",
  "05004002",
  "03004002",
  "05004040",
  "0300400A",
  "05004041",
  "05008036",
  "03008011",
  "07FF8005",
  "07FFC008",
  "0500400A",
  "0C00402C",
  "03008005",
  "05004007",
  "07FF8004",
  "07FF8011",
  "05004031",
  "10014001",
  "03008003",
  "0500402A",
  "05014039",
  "03008006",
  "05014032",
  "05004004",
  "03008017",
  "05014038",
  "05004037",
  "05004043",
  "0300800D",
  "07FF8007",
  "03008008",
  "10018003",
  "03008019",
  "05004033",
  "03008013",
  "03004066",
  "03004013",
  "07FFC003",
  "03008002",
  "05004009",
  "05004005",
  "0500400B",
  "05004001",
  "18FF8005",
  "05014035",
  "10014002",
  "0300400D",
  "03008009",
  "0C00C004",
  "05024001",
  "05004038",
  "0C00C003",
  "03008014",
  "0500400D",
  "05024004",
  "0300800F",
  "03008001",
  "0C00C006",
  "0500400C",
  "05014033",
  "03004067",
  "07FF8010",
  "03004020",
  "03004006",
  "0500402E",
  "10018004",
  "0C008001",
  "03004009",
  "0300400E",
  "1000C003",
  "0C008005",
  "07FFC00A",
  "03008000",
  "05004014",
  "0C00402D",
  "0C008009",
  "03008016",
  "05014031",
  "03008004",
  "05004042",
  "05004008",
  "0500C010",
  "0300800C",
  "0500402D",
  "0300400B",
  "03004001",
  "1000C002",
  "0300800A",
  "03004008",
  "1000C001",
  "05004015",
  "03008007",
  "0502400D",
  "03004014",
  "05004012",
  "05004013",
  "05004030",
  "0500400F",
  "05004010",
  "05004011",
  "050240A3",
  "050140A3",
  "050040A3",
  "050340A3",
  "05008041",
  "05008040",
  "0502C014",
  "0502C024",
  "0502C026",
  "05004057"
};

const char *device_error_values[] PROGMEM = {
  "The AMS has been disabled for a print, but it still has filament loaded. Please unload the AMS filament and switch to the spool holder filament for printing.",
  "Please pull out the filament on the spool holder. If this message persists, please check to see if there is filament broken in the extruder. (Connect a PTFE tube if you are about to use an AMS.)",
  "Z axis homing failed; the task has been stopped.",
  "The cutter is stuck. Please make sure the cutter handle is out and check the filament sensor cable connection.",
  "Printing was cancelled.",
  "Failed to download print job; please check your network connection.",
  "There is not enough free storage space for the print job. Restoring to factory settings can free up available space.",
  "Printing stopped because the printer was unable to parse the file. Please resend your print job.",
  "The slicing progress has not been updated for a long time, and the printing task has exited. Please confirm the parameters and reinitiate printing.",
  "The task was canceled.",
  "Chamber temperature malfunction.",
  "Unsupported print file path or name. Please resend the print job.",
  "Auto Bed Leveling failed; the task has been stopped.",
  "The printer has reached its power limit. Please connect a dedicated power adapter to this AMS to enable drying.",
  "Mechanical resonance frequency identification failed.",
  "The AMS drying cannot be started during printing.",
  "Your sliced file is not consistent with the current printer model. Continue?",
  "Detected build plate is not the same as the Gcode file. Please adjust slicer settings or use the correct plate.",
  "Failed to feed the filament outside the AMS. Please clip the end of the filament flat and check to see if the spool is stuck.",
  "Please pull out the filament on the spool holder. If this message persists, please check to see if there is filament broken in the extruder. (Connect a PTFE tube if you are about to use an AMS)",
  "The file name is not supported. Please rename and restart the print job.",
  "Device data link error. Please reboot the printer.",
  "Toolhead front cover fell off. Please remount the front cover and check to make sure your print is going okay.",
  "The device requires a repair upgrade, and printing is currently unavailable.",
  "Failed to pull back the filament from the toolhead to AMS. Please check whether the filament or the spool is stuck.",
  "External filament has run out; please load a new filament.",
  "The accessory firmware does not match the printer. Please upgrade it on the \"Firmware\" page.",
  "Timelapse is not supported as Spiral Vase mode is enabled in slicing presets.",
  "Spaghetti defects were detected by the AI Print Monitoring. Please check the quality of the printed model before continuing your print.",
  "Failed to connect to the router, which may be caused by wireless interference or being too far away from the router. Please try again or move the printer closer to the router and try again.",
  "Device login has expired; please try to bind again.",
  "The build plate marker was not detected. Please confirm the build plate is correctly positioned on the heatbed with all four corners aligned, and the marker is visible.",
  "QR code binding is in progress, so device discovery binding cannot be performed. You can scan the QR code on the screen for binding or exit the QR code display page on screen and try device discovery binding.",
  "Device is busy and cannot start new task. Please wait for current task to complete before sending new task.",
  "Foreign objects detected on heatbed. Please check and clean the heatbed. Then, select \"Resume\" to resume the print job.",
  "The regional settings do not match the printer; please check the printer's regional settings.",
  "Your sliced file is not compatible with current printer model. This file can't be printed on this printer.",
  "Due to power limitations, only one AMS is allowed to use the device's power for drying.",
  "Detected that the extruder is not extruding normally. If the defects are acceptable, select \"Resume\" to resume the print job.",
  "Please observe the nozzle. If the filament has been extruded, select \"Done\"; if not, please push the filament forward slightly, and then select \"Retry\".",
  "Nozzle temperature malfunction",
  "The time-lapse mode is set to Traditional in the slicing file. This may cause surface defects. Would you like to enable it?",
  "No build plate is placed.",
  "The AMS firmware does not match the printer. Please upgrade it on the \"Firmware\" page.",
  "Printing paused due to the pause command added to the printing file.",
  "Calibration of motion precision failed.",
  "Printing cannot be initiated while AMS is drying.",
  "Please pull out the filament on the spool holder. If this message persists, please check to see if there is filament broken in the extruder or PTFE tube. (Connect a PTFE tube if you are about to use an AMS)",
  "First layer defects were detected by the Micro Lidar. Please check the quality of the printed model before continuing your print.",
  "Print jobs are not allowed to be sent while updating logs.",
  "Print jobs are not allowed to be sent while updating firmware.",
  "There was a problem downloading a file. Please check your network connection and resend the print job.",
  "Failed to connect to Bambu Cloud. Please check your network connection.",
  "Failed to feed the filament outside the AMS-HT. Please clip the end of the filament flat and check to see if the spool is stuck.",
  "The device is in the process of binding and cannot respond to new binding requests.",
  "Timelapse is not supported as the Print sequence is set to \"By object\".",
  "Resume failed after power loss.",
  "Heatbed temperature malfunction",
  "Possible spaghetti failure was detected.",
  "Current filament will be used in this print job. Settings cannot be changed.",
  "The nozzle diameter in sliced file is not consistent with the current nozzle setting. This file can't be printed.",
  "Possible defects were detected in the first layer.",
  "The nozzle is covered with filament, or the build plate is installed incorrectly. Please cancel this print and clean the nozzle or adjust the build plate according to the actual status. You can also select \"Resume\" to resume the print job.",
  "Please run a self-test and restart the print job.",
  "Some features are not supported by the current device. Please check the Studio feature settings or update the firmware to the latest version.",
  "The door seems to be open, so printing was paused.",
  "Printing was paused by the user. You can select \"Resume\" to continue printing.",
  "Purged filament may have piled up in the waste chute.",
  "Please insert a MicroSD card and restart the print job.",
  "Your APP region does not match with your printer; please download the APP in the corresponding region and register your account again.",
  "Calibration result is over the threshold.",
  "Check if the external filament spool or filament is stuck.",
  "The nozzle presence detection failed. Please check the Assistant for details.",
  "The nozzle is clogged.",
  "The system does not support the file system currently used by the MicroSD card. Please replace the MicroSD card or format it to FAT32.",
  "Prime Tower is not enabled and time-lapse mode is set to Smooth in slicing file. This may cause surface defects. Would you like to enable it?",
  "First layer defects were detected. If the defects are acceptable, select \"Resume\" to resume the print job.",
  "Homing XY axis failed.",
  "The motor self-check failed.",
  "Enabling Timelapse in traditional mode may cause defects; please activate this feature as needed.",
  "Purged filament has piled up in the waste chute, which may cause a tool head collision.",
  "Please observe the nozzle. If the filament has been extruded, select \"Continue\"; if not, please push the filament forward slightly and then select \"Retry\".",
  "Printing was paused for unknown reason. You can select \"Resume\" to resume the print job.",
  "Slicing for the print job failed. Please check your settings and restart the print job.",
  "The toolhead camera is not working properly; please reboot the device.",
  "Build plate localization marker was not found.",
  "The nozzle is clogged with filament. Please cancel this print and clean the nozzle or select \"Resume\" to resume the print job.",
  "Device discovery binding is in progress, and the QR code cannot be displayed on the screen. You can wait for the binding to finish or abort the device discovery binding process in the APP/Studio and retry scanning the QR code on the screen for binding.",
  "Filament ran out. Please load new filament.",
  "Printing and calibration cannot be performed while the AMS is drying. Please stop the drying process or connect a power adapter to any AMS unit not used for the current print, then try again.",
  "Starting printing failed; please power cycle the printer and resend the print job.",
  "MicroSD Card read/write exception: please reinsert or replace the MicroSD Card.",
  "Skipped step detected: auto-recover complete; please resume print and check if there are any layer shift problems.",
  "System exception",
  "Internal communication exception",
  "The printer timed out waiting for the nozzle to cool down before homing.",
  "Printing CF material with stainless steel may cause nozzle damage.",
  "A Filament pile-up was detected by AI Print Monitoring. Please clean filament from the waste chute.",
  "The AMS failed to change filament.",
  "High bed temperature may lead to filament clogging in the nozzle. You may open the chamber door.",
  "There is not enough free storage space for the print job. Please format or clear files from the MicroSD card to free up space.",
  "There was an unfinished print job when the printer lost power. If the model is still adhered to the build plate, you can try resuming the print job.",
  "Failed to start a new task: filament loading/unloading not completed.",
  "Homing Z axis failed: temperature control abnormality.",
  "The device is printing and cannot be upgraded at the moment. Please try again later.",
  "AMS is in operation and cannot be upgraded at the moment. Please try again when it is idle.",
  "The device is currently upgrading. Please try again when it is idle.",
  "AMS is initializing and cannot be upgraded at the moment. Please try again later.",
  "AMS is drying and cannot be upgraded at the moment. Please try again later.",
  "The printer is loading or unloading filament and cannot be upgraded at the moment. Please try again later.",
  "AMS(or AMS lite) C communication is abnormal. Please reconnect the module cable or restart the printer.",
  "AMS(or AMS lite) B communication is abnormal. Please reconnect the module cable or restart the printer.",
  "AMS(or AMS lite) A communication is abnormal. Please reconnect the module cable or restart the printer.",
  "AMS(or AMS lite) D communication is abnormal. Please reconnect the module cable or restart the printer.",
  "The filament in hotend is too cold. Extrusion may damage the extruder. Still feeding in/out the filament?",
  "Toolhead front cover is detached. Moving the toolhead may damage the printer. Do you want to continue?",
  "The AMS Remaining Filament Estimation is enabled by default and cannot be disabled.",
  "The flow dynamic calibration records have exceeded the storage limit. Please delete some historical records in the slicer software before adding new calibration data.",
  "The device is busy with the current task and cannot perform this operation for now. Please try again later.",
  "The filament selected in the slicer requires a harder nozzle. Please replace the nozzle or adjust the filament settings before reprinting."
};
